baseurl = "https://nathaniel-roberts.github.io/"
title = "Nathaniel Roberts"
theme = "hugo-coder"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Nathaniel Roberts"
  info = "Systems Engineer and CyberSecurity Enthusiast"
  description = "Nathaniel Roberts's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

#  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png" 
  favicon_16 = "/images/favicon-16x16.png"

  dateFormat = "January 2, 2006"
  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Nathaniel-Roberts/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://linkedin.com/in/nathaniel-g-roberts/"


# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
[[menu.main]]
name = "About"
weight = 3
url = "about/"
[[menu.main]]
name = "Contact Me"
weight = 4
url = "contact/"

# Comments
[comments]
  # Comment provider:
  provider = "giscus"

  # Which page types are commentable?
  commentable = {posts = true, projects = false}

  # Configuration of giscus
  [comments.giscus]
    repo = "Nathaniel-Roberts/Nathaniel-Roberts.github.io"
    repoID = "R_kgDOI1dzaQ"
    category = "Announcements"
    categoryID = "DIC_kwDOI1dzac4Cgh9i"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "noborder_dark"
    lang = "en"
    loading = "lazy"